# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_interface_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(False)
        self.setFixedSize(self.width(), self.height())  #设置固定大小
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 150, 91, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.widget_top = QtWidgets.QWidget(self.centralwidget)
        self.widget_top.setGeometry(QtCore.QRect(0, 0, 700, 20))
        self.widget_top.setStyleSheet("QWidget#widget_top{background:rgb(0, 170, 255)}\n"
"color: rgb(0, 170, 255);")
        self.widget_top.setObjectName("widget_top")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_top)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.v_line = QtWidgets.QFrame(self.centralwidget)
        self.v_line.setGeometry(QtCore.QRect(80, 20, 20, 541))
        self.v_line.setStyleSheet("Qline#v_line{background:rgb(0, 170, 255)}\n"
"color: rgb(0, 170, 255);")
        self.v_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.v_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.v_line.setObjectName("v_line")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(90, 40, 610, 520))
        self.stackedWidget.setAcceptDrops(True)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(70, 20, 144, 16))
        self.label_5.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.page_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(70, 30, 521, 411))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_8.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";")
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.radioButton_2 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButton_2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.radioButton = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton.setObjectName("radioButton")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radioButton)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.radioButton_3 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radioButton_3)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.radioButton_4 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.radioButton_4)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";")
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.label_12)
        self.radioButton_5 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.radioButton_5)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.radioButton_6 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.radioButton_6)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.radioButton_7 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.radioButton_7)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.radioButton_8 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_8.setObjectName("radioButton_8")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.radioButton_8)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_17.setStyleSheet("font: 63 9pt \"Segoe UI Semibold\";")
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.label_17)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.radioButton_11 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_11.setObjectName("radioButton_11")
        self.formLayout_3.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.radioButton_11)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.radioButton_10 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_10.setObjectName("radioButton_10")
        self.formLayout_3.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.radioButton_10)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.radioButton_9 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_9.setObjectName("radioButton_9")
        self.formLayout_3.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.radioButton_9)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.radioButton_12 = QtWidgets.QRadioButton(self.formLayoutWidget_3)
        self.radioButton_12.setObjectName("radioButton_12")
        self.formLayout_3.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.radioButton_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 430, 211, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.layoutWidget1 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 20, 261, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_24 = QtWidgets.QLabel(self.splitter_3)
        self.label_24.setObjectName("label_24")
        self.comboBox_2 = QtWidgets.QComboBox(self.splitter_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_21 = QtWidgets.QLabel(self.splitter_4)
        self.label_21.setObjectName("label_21")
        self.comboBox_1 = QtWidgets.QComboBox(self.splitter_4)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.verticalLayout.addWidget(self.splitter_4)
        self.splitter_5 = QtWidgets.QSplitter(self.layoutWidget1)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_22 = QtWidgets.QLabel(self.splitter_5)
        self.label_22.setObjectName("label_22")
        self.comboBox_3 = QtWidgets.QComboBox(self.splitter_5)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.splitter_5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.listView = QtWidgets.QListView(self.page_4)
        self.listView.setGeometry(QtCore.QRect(80, 50, 421, 371))
        self.listView.setObjectName("listView")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "喜好偏向"))
        self.pushButton_2.setText(_translate("MainWindow", "输入预期"))
        self.pushButton.setText(_translate("MainWindow", "结果推荐"))
        self.pushButton_3.setText(_translate("MainWindow", "其他"))
        self.v_line.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic; color:#55aaff;\">Welcome to CBR programme</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Which of the following attributes do you think is the most important?</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "U value"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.label_7.setText(_translate("MainWindow", "Complexity"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.label_10.setText(_translate("MainWindow", "Insulation"))
        self.radioButton_3.setText(_translate("MainWindow", "RadioButton"))
        self.label_11.setText(_translate("MainWindow", "Coagulability"))
        self.radioButton_4.setText(_translate("MainWindow", "RadioButton"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Which of the following attributes do you think is the second important?</p></body></html>"))
        self.radioButton_5.setText(_translate("MainWindow", "RadioButton"))
        self.label_14.setText(_translate("MainWindow", "Complexity"))
        self.radioButton_6.setText(_translate("MainWindow", "RadioButton"))
        self.label_15.setText(_translate("MainWindow", "Insulation"))
        self.radioButton_7.setText(_translate("MainWindow", "RadioButton"))
        self.label_16.setText(_translate("MainWindow", "Coagulability"))
        self.radioButton_8.setText(_translate("MainWindow", "RadioButton"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Which of the following attributes do you think is the third important?</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "U value"))
        self.radioButton_11.setText(_translate("MainWindow", "RadioButton"))
        self.label_20.setText(_translate("MainWindow", "Complexity"))
        self.radioButton_10.setText(_translate("MainWindow", "RadioButton"))
        self.label_18.setText(_translate("MainWindow", "Insulation"))
        self.radioButton_9.setText(_translate("MainWindow", "RadioButton"))
        self.label_23.setText(_translate("MainWindow", "Coagulability"))
        self.radioButton_12.setText(_translate("MainWindow", "RadioButton"))
        self.label_13.setText(_translate("MainWindow", "U value"))
        self.pushButton_6.setText(_translate("MainWindow", "execute"))
        self.pushButton_5.setText(_translate("MainWindow", "add"))
        self.label.setText(_translate("MainWindow", "Case Name           "))
        self.label_2.setText(_translate("MainWindow", "U value             "))
        self.label_24.setText(_translate("MainWindow", "Complexity          "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "very low"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "low"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "medium"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "high"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "very high"))
        self.label_21.setText(_translate("MainWindow", "Insulation          "))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "very low"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "low"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "medium"))
        self.comboBox_1.setItemText(3, _translate("MainWindow", "high"))
        self.comboBox_1.setItemText(4, _translate("MainWindow", "very high"))
        self.label_22.setText(_translate("MainWindow", "Coagulability       "))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "very low"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "low"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "medium"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "high"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "very high"))

if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()  #  ui_from是类名
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
